# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.bgvaralg <- function(object) {
    .Call(`_bgvars_bgvaralg`, object)
}

.bgvartvpalg <- function(object) {
    .Call(`_bgvars_bgvartvpalg`, object)
}

.bgvecalg <- function(object) {
    .Call(`_bgvars_bgvecalg`, object)
}

.bgvectvpalg <- function(object) {
    .Call(`_bgvars_bgvectvpalg`, object)
}

.ir <- function(A, h, impulse, response) {
    .Call(`_bgvars_ir`, A, h, impulse, response)
}

.vardecomp <- function(A, h, response) {
    .Call(`_bgvars_vardecomp`, A, h, response)
}

