# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ir <- function(A, h, impulse, response, full) {
    .Call(`_bgvars_ir`, A, h, impulse, response, full)
}

#' Calculates the log-likelihood of a multivariate normal distribution.
#' 
#' @param u a \eqn{K \times T} matrix of residuals.
#' @param sigma a \eqn{K \times K} or \eqn{KT \times K} variance-covariance matrix.
#' 
#' @examples
#' data("e1", package = "bvartools")
#' e1 <- diff(log(e1))
#' 
#' # Generate VAR model
#' data <- bvartools::gen_var(e1, p = 2, deterministic = "const")
#' y <- data$Y
#' x <- data$Z
#'
#' # LS estimate
#' ols <- tcrossprod(y, x) %*% solve(tcrossprod(x))
#' 
#' # Residuals
#' u <- y - ols %*% x # Residuals
#'
#' # Covariance matrix
#' sigma <- tcrossprod(u) / ncol(u)
#' 
#' # Log-likelihood
#' loglik_normal(u = u, sigma = sigma)
#' 
loglik_normal <- function(u, sigma) {
    .Call(`_bgvars_loglik_normal`, u, sigma)
}

