# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.bgvaralg <- function(object) {
    .Call(`_bgvars_bgvaralg`, object)
}

.draw_forecast <- function(i, k, a0, a, b_, c_, sigma, pred) {
    .Call(`_bgvars_draw_forecast`, i, k, a0, a, b_, c_, sigma, pred)
}

.gir <- function(A, h, impulse, response) {
    .Call(`_bgvars_gir`, A, h, impulse, response)
}

.ir <- function(A, h, type, impulse, response) {
    .Call(`_bgvars_ir`, A, h, type, impulse, response)
}

.vardecomp <- function(A, h, response) {
    .Call(`_bgvars_vardecomp`, A, h, response)
}

